- name: Register Node with RHN
  redhat_subscription:
    state: present
    username: "{{ rhn_user }}"
    password: "{{ rhn_password }}"
    pool: "{{ rhn_pool }}"
- name: Configure Repositories - Disable All
  rhsm_repository:
    name: '*'
    state: disabled
- name: Configure Repositories - Enable RHEL 7
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items:
    - rhel-7-server-extras-rpms
    - rhel-7-server-rh-common-rpms
    - rhel-7-server-rpms
  when: ansible_facts['cmdline']['BOOT_IMAGE'] is search('vmlinuz-3')
- name: Configure Repositories - Enable RHEL 8
  rhsm_repository:
    name: "{{ item }}"
    state: enabled
  with_items:
    - rhel-8-for-x86_64-baseos-rpms
    - rhel-8-for-x86_64-appstream-rpms
  when: ansible_facts['cmdline']['BOOT_IMAGE'] is search('vmlinuz-4')
- name: Update all packages
  yum:
    name: '*'
    state: latest
