---
- name: Generate default templates
  hosts: all
  become: yes
  vars:
    rhn_installer_local_config: /var/lib/awx/projects/rh_installer.local/config.yml
  include_vars:
    file: roles/director/vars/main.yml
  include_tasks:
    file: roles/director/tasks/90-create_overcloud_templates.yml
