- name: Update all packages
  yum:
    name: '*'
    state: latest
  become: yes
- name: Install Triple-O packages (OSP Version {{ osp_version }} <= 14) (RHEL7)
  yum:
    name: python-tripleoclient
    state: latest
  when: osp_version <= 14 and ansible_facts['cmdline']['BOOT_IMAGE'] is search('vmlinuz-3')
  become: yes
- name: Install Triple-O packages (OSP Version {{ osp_version }} >= 15) (RHEL8)
  yum:
    name: python3-tripleoclient
    state: latest
  when: osp_version >= 15 and ansible_facts['cmdline']['BOOT_IMAGE'] is search('vmlinuz-4')
  become: yes
- name: Install Ceph Ansible package (OSP Version {{ osp_version }} >= 13)
  yum:
    name: ceph-ansible
    state: latest
  when: osp_version >= 13
  become: yes
- name: Install Director Image Packages for the Overcloud and some configuration tooling
  yum:
    name: '{{ packages }}'
    state: latest
  vars:
    packages:
      - rhosp-director-images
      - rhosp-director-images-ipa
      - libguestfs-tools
      - crudini
  become: yes
