- name: Generate container registry files to be used during Director installation (OSP Version {{ osp_version }} >= 14)
  block:
    - name: Generate default container image preparation file (OSP Version {{ osp_version }})
      shell: |
        openstack tripleo container image prepare default \
          --local-push-destination \
          --output-env-file /home/{{ uc_user }}/container_data/containers-prepare-parameter.yaml
      when: registry_type == "local"
    - name: Generate default container image preparation file (OSP Version {{ osp_version }})
      shell: |
        openstack tripleo container image prepare default \
          --output-env-file /home/{{ uc_user }}/container_data/containers-prepare-parameter.yaml
      when: registry_type == "remote"
    - name: Copy the containers-prepare-parameter.yaml into the templates directory (OSP Version {{ osp_version }})
      copy:
        src: /home/{{ uc_user }}/container_data/containers-prepare-parameter.yaml
        dest: /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
        owner: "{{ uc_user }}"
        group: "{{ uc_user }}"
        mode: 0644
        remote_src: yes
    - name: Add container image preparation file to undercloud.conf (OSP Version {{ osp_version }})
      shell: |
        crudini --set /home/{{ uc_user }}/undercloud.conf DEFAULT container_images_file /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
  when: osp_version >= 14
  become: yes
  become_user: "{{ uc_user }}"
