- name: Create a containers subdirectory for intermediate work files (OSP Version {{ osp_version }} >= 12)
  file:
    state: directory
    path: /home/{{ uc_user }}/container_data
    owner: "{{ uc_user }}"
    group: "{{ uc_user }}"
    mode: u+rwx,g+rx,o+rx
  when: osp_version >= 12
  become: yes
  become_user: "{{ uc_user }}"
- name: Generate container registry files to be used during Director installation (OSP Version {{ osp_version }} >= 14)
  block:
    - name: Generate default container image preparation file (OSP Version {{ osp_version }} >= 14)
      shell: |
        openstack tripleo container image prepare default \
          --local-push-destination \
          --output-env-file /home/{{ uc_user }}/container_data/containers-prepare-parameter.yaml
      when: container_registry == "local"
    - name: Generate default container image preparation file (OSP Version {{ osp_version }} >= 14)
      shell: |
        openstack tripleo container image prepare default \
          --output-env-file /home/{{ uc_user }}/container_data/containers-prepare-parameter.yaml
      when: container_registry == "remote"
    - name: Copy the containers-prepare-parameter.yaml into the templates directory (OSP Version {{ osp_version }} >= 14)
      copy:
        src: /home/{{ uc_user }}/container_data/containers-prepare-parameter.yaml
        dest: /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
        owner: "{{ uc_user }}"
        group: "{{ uc_user }}"
        mode: 0644
        remote_src: true
    - name: Add registry authentication to containers-prepare-parameter.yaml in templates directory (OSP Version {{ osp_version }} >= 14)
      shell: |
        echo "  ContainerImageRegistryCredentials:" | tee -a /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
        echo "    {{ registry_hostname }}:" | tee -a /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
        echo "      {{ registry_user }}: {{ registry_password }}" | tee -a /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
    - name: Add container image preparation file to undercloud.conf (OSP Version {{ osp_version }} >= 14)
      shell: |
        crudini --set /home/{{ uc_user }}/undercloud.conf DEFAULT container_images_file /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
    - name: Update repositories and registries to support an OSP Beta Release
      shell: | 
        sed -i 's/registry.redhat.io\/rhosp{{ osp_version }}/registry.redhat.io\/rhosp-beta/g' /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
        sed -i 's/ceph_namespace: docker-registry.upshift.redhat.com\/ceph/ceph_namespace: registry.redhat.io\/rhceph-beta/g' /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
        sed -i 's/ceph_image: rhceph-4.0-rhel8/ceph_image: {{ ceph_image }}/g' /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
        sed -i "/push_destination: true/a\    excludes:\n      - grafana" /home/{{ uc_user }}/templates/containers-prepare-parameter.yaml
      when: osp_version == osp_beta_version and osp_version == 16
  when: osp_version >= 14
  become: yes
  become_user: "{{ uc_user }}"
