- name: Check if Director is Deployed
  shell: |
         if [[ -f ~/stackrc ]]
         then
           source ~/stackrc >/dev/null 2>&1
           openstack user list >/dev/null 2>&1
           echo $?
         else
           echo 1
         fi
  register: undercloud_test
  become: yes
  become_user: "{{ uc_user }}"
- name: Deploy director (if not deployed) (OSP Version {{ osp_version }} <= 14)
  shell: |
         cd /home/{{ uc_user }}/
         openstack undercloud install
  become: yes
  become_user: "{{ uc_user }}"
  when: undercloud_test.stdout != '0' and osp_verion <= 14
- name: Deploy director (if not deployed) (OSP Version {{ osp_version }} >= 15)
  shell: |
         cd /home/{{ uc_user }}/
         echo '{{ rhn_password }}' | podman login -u {{ rhn_user }} --password-stdin https://registry.redhat.io
         openstack undercloud install
  become: yes
  become_user: "{{ uc_user }}"
  when: undercloud_test.stdout != '0' and osp_version >= 15
